arch: "slow"
image_size: 256
frames_per_clip: 8
temporal_downsampling: 8
resnet_depth: 50
resnet_num_groups: 1
resnet_width_per_group: 64
resnet_dropout_rate: 0.5
resnet_fc_std_init: 0.01
resnet_final_batchnorm_zero_init: 1
weight_decay: 1e-4
learning_rate: 0.1 # for 8 GPUs with batch_size 64
max_epochs: 196